services:
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://vibelms:${POSTGRES_PASSWORD}@postgres:5432/vibelms
      - SESSION_SECRET=${SESSION_SECRET}
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=vibelms
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=vibelms
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    networks:
      - vibelms-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vibelms
      - POSTGRES_USER=vibelms
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibelms -d vibelms"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - vibelms-network

volumes:
  postgres_data:
    driver: local

networks:
  vibelms-network:
    driver: bridge